<?php
declare(strict_types=1);

const BA_ROOT = 'C:\\inetpub\\BackAisle';
const BA_DB = BA_ROOT . '\\data\\backaisle.db';
const BA_CONFIG = BA_ROOT . '\\config\\config.php';

function ba_config(): array {
    static $cfg = null;
    if (is_array($cfg)) {
        return $cfg;
    }
    if (is_file(BA_CONFIG)) {
        $loaded = include BA_CONFIG;
        if (is_array($loaded)) {
            $cfg = $loaded;
            return $cfg;
        }
    }
    $cfg = [
        'installed' => false,
        'org_name' => 'BackAisle',
        'db' => [
            'driver' => 'sqlite',
            'path' => BA_DB,
        ],
    ];
    return $cfg;
}

function ba_is_installed(): bool {
    $c = ba_config();
    if (!empty($c['installed']) && is_file(BA_CONFIG)) {
        return true;
    }
    if (is_file(BA_DB)) {
        try {
            $pdo = new PDO('sqlite:' . BA_DB, null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            $n = (int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();
            return $n > 0;
        } catch (Throwable $e) {
            return false;
        }
    }
    return false;
}

function ba_write_config(array $cfg): void {
    $dir = BA_ROOT . DIRECTORY_SEPARATOR . 'config';
    if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
        throw new RuntimeException('Cannot create config directory. Grant Modify to the IIS app pool on C:\\inetpub\\BackAisle\\config.');
    }
    $export = var_export($cfg, true);
    $php = "<?php\ndeclare(strict_types=1);\n/** Generated by setup.php — do not commit. */\nreturn {$export};\n";
    $path = $dir . DIRECTORY_SEPARATOR . 'config.php';
    if (@file_put_contents($path, $php) === false) {
        throw new RuntimeException('Could not write config/config.php.');
    }
    $json = [
        'driver' => $cfg['db']['driver'] ?? 'sqlite',
        'path' => $cfg['db']['path'] ?? BA_DB,
        'host' => $cfg['db']['host'] ?? 'localhost',
        'port' => (int)($cfg['db']['port'] ?? 1433),
        'database' => $cfg['db']['database'] ?? 'BackAisle',
        'username' => $cfg['db']['username'] ?? '',
        'password' => $cfg['db']['password'] ?? '',
        'encrypt' => !empty($cfg['db']['encrypt']),
        'trust_server_certificate' => !empty($cfg['db']['trust_server_certificate']),
        'odbc_driver' => $cfg['db']['odbc_driver'] ?? 'ODBC Driver 18 for SQL Server',
    ];
    @file_put_contents($dir . DIRECTORY_SEPARATOR . 'collector.json', json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
}

function ba_secrets(): array {
    $paths = [
        getenv('BACKAISLE_SECRETS') ?: '',
        'C:\\ProgramData\\BackAisle\\secrets.env',
        BA_ROOT . '\\secrets.env',
    ];
    $out = [];
    foreach ($paths as $p) {
        if ($p === '' || !is_file($p)) {
            continue;
        }
        foreach (file($p, FILE_IGNORE_NEW_LINES) as $line) {
            $line = trim($line);
            if ($line === '' || $line[0] === '#' || !str_contains($line, '=')) {
                continue;
            }
            [$k, $v] = explode('=', $line, 2);
            $out[trim($k)] = trim($v);
        }
        break;
    }
    return $out;
}

function ba_audit(PDO $db, string $action, ?string $entity = null, ?string $id = null, ?string $details = null): void {
    $st = $db->prepare('INSERT INTO audit_log (username, action, entity, entity_id, details) VALUES (?,?,?,?,?)');
    $st->execute([$_SESSION['user']['username'] ?? null, $action, $entity, $id, $details]);
}

$sessionDir = BA_ROOT . DIRECTORY_SEPARATOR . 'data' . DIRECTORY_SEPARATOR . 'sessions';
if (!is_dir($sessionDir)) {
    @mkdir($sessionDir, 0775, true);
}
if (is_dir($sessionDir)) {
    session_save_path($sessionDir);
}
session_name('BACKAISLE');
if (session_status() !== PHP_SESSION_ACTIVE) {
    @session_start();
}
